### ISSUE TITLE
Models::SolidusGlobalize::Spree::TaxonomyDecorator (NameError)

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_globalize#108]
_Originally opened  by @wayferer here: https://github.com/solidusio/solidus_support/issues/26_

It was suggested on Slack to make an issue here. The project is running fine locally but when pushed to Heroku I'm getting the following error:

```
/app/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.2.1/lib/zeitwerk/loader.rb:351:in `const_get': uninitialized constant Models::SolidusGlobalize::Spree::TaxonomyDecorator (NameError)

Did you mean?  Models::SolidusGlobalize::Spree::TaxonomyDecorator

Models::SolidusGlobalize::Spree::TaxonDecorator
```

Have I overlooked a command to run? I've run the migrations, seeds and sample product commands against the Heroku app.

```
heroku addons:create heroku-postgresql:hobby-dev
heroku run rake db:migrate
heroku run rake db:seed
heroku run rake spree_sample:load
```

Thanks.

Edit: Sometimes I also get this error:

```
/app/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.2.1/lib/zeitwerk/loader.rb:351:in `const_get': uninitialized constant Controllers::SolidusGlobalize::Spree::BaseControllerDecorator (NameError)

Did you mean? Controllers::SolidusGlobalize::Spree::BaseControllerDecorator
```

**Comment by wayferer** [comment]
@kennyadsl thanks for sorting this out. Do you have an idea of when it will be merged and something we can use? Thanks again.
