### ISSUE TITLE
Solidus 3.0 compatibility

### ISSUE THREAD

**Issue by jfturcot** [solidusio-contrib/solidus_globalize#141]
I would love to upgrade my Solidus project to 3.0, but this Gem is the only one I use that is stopping me to do so. Is there a lot of work to get it working for 3.0 or do we only need to update the gemspec? Anything I can help with? Thanks!

**Comment by kennyadsl** [comment]
Hey! Which problem are you having exactly with 3.0?

**Comment by jfturcot** [comment]
The problem I am having is something I just saw you fixed on your ``kennyadsl/solidus-3`` branch.

It is about the gemspec requiring a less than 3.0 on solidus_core:
``
s.add_dependency 'solidus_core', ['>= 2.0.0', '< 3']
``

I guess I could just use your branch until it's merged into master, thanks!

**Comment by Mateus-Resende** [comment]
🆙 
do we have an update about this gem update?

**Comment by mrbrdo** [comment]
@kennyadsl is this gem dead?

**Comment by kennyadsl** [comment]
@mrbrdo I don't think so, I have something in the work in #142, waiting for the routing-filter gem to release a version compatible with Rails 6.1. Apparently, [this happened a while ago](https://github.com/svenfuchs/routing-filter/commit/3ce9a7eb8d6f3e9c2ce1e66ca1c21da4a56a60ed) and I missed it. Will try to take a look as soon as possible.

**Comment by kennyadsl** [comment]
Specs are green, should be fixed now. Let me know if there are still issues.

**Comment by jarednorman** [comment]
Yeah, we're running this gem on a variety of stores and it works great. We're actually hoping to upstream some of our improvements soon.
