### ISSUE TITLE
Undefined method 'find_by_permalink' in Taxon's navigation

### ISSUE THREAD

**Issue by ghost** [solidusio-contrib/solidus_globalize#18]
Hello everyone,
We're getting this error with solidus 1.4 and solidus_globalize when trying to view products of a taxon in the frontend (http://solidus/t/whatever/whatever):

![solglob1](https://cloud.githubusercontent.com/assets/22205990/19724737/3cc4328a-9b82-11e6-8491-064a3ecf2d76.PNG)

We suppose that permalink attribute doesn't exist in Taxon class because of globalize gem (permalink is translatable).
So, we resolve temporarily this issue adding a decorator to TaxonController, replacing find_by_permalink call for:

`@taxon = Spree::Taxon.where(permalink: params[:id]).first`

But we don't know if this is the best solution.
Thanks.

**Comment by AndreiMotinga** [comment]
same here

**Comment by kennyadsl** [comment]
This issue has been fixed on Solidus core with https://github.com/solidusio/solidus/commit/2c775ab24e592b3949de417712017c1adb4de3f9#diff-e347d1aa8c38912a1e2a270a429fbea8.
