### ISSUE TITLE
uninitialized constant SolidusGlobalize::ControllerGlobalizeHelper::Fallbacks

### ISSUE THREAD

**Issue by bofrede** [solidusio-contrib/solidus_globalize#22]
GET /
Results in:
NameError in Spree::HomeController#index
uninitialized constant SolidusGlobalize::ControllerGlobalizeHelper::Fallbacks

In bundler/gems/solidus_globalize-1538996926f2/app/controllers/concerns/solidus_globalize/controller_globalize_helper.rb
```ruby
def globalize_fallbacks
  Fallbacks.config!
end
```

This only happens in environments that have:
```ruby
config.cache_classes = true
config.eager_load = true
```
## Setup
ruby 2.4.0
rails 5.0.2
solidus 2.1.0
solidus_auth_devise 1.6.2
solidusio-contrib/solidus_i18n@4abcb7a5747fffa4a3555d212d045d0eec19f0af
solidusio-contrib/solidus_globalize@1538996926f2a2cef69140c6c19c1fda0eb6a775
globalize/globalize@2fd4270b322f2dbc619441aacdfc8352caa183a9

Any suggestions how to resolve it?

**Comment by quake** [comment]
please try to add this line to config/initializers/i18n_related_initializer.rb
```
require 'solidus_globalize/fallbacks'
```

and I think this line should be added to gem lib/solidus_globalize.rb

**Comment by kennyadsl** [comment]
This should be autoloaded with https://github.com/solidusio-contrib/solidus_globalize/blob/949779f8d446aa1269927514884085408b4c4b92/lib/solidus_globalize/engine.rb#L10. Is anyone still experiencing this?
