### ISSUE TITLE
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column friendly_id_slugs.locale does not exist

### ISSUE THREAD

**Issue by weblike-guy** [solidusio-contrib/solidus_globalize#48]
![screen shot 2560-05-22 at 7 11 35 pm](https://cloud.githubusercontent.com/assets/8809681/26308454/83189790-3f23-11e7-8a90-071d6616b382.png)

![screen shot 2560-05-22 at 7 26 58 pm](https://cloud.githubusercontent.com/assets/8809681/26308763/aaf97314-3f24-11e7-8254-b3ed8b121f86.png)

when I try to make new product from admin page , put all info and push create, then appear this error...
another link is no problem ..

looks like column friendly_id_slugs.locale is don't exist .....

I have no idea how to fix this issue..

pls help me

**Comment by AndreiMotinga** [comment]
https://github.com/norman/friendly_id-globalize

run 
```
rails generate friendly_id_globalize
rake db:migrate
```

**Comment by weblike-guy** [comment]
Thanks. I pass the create product but next problem ...

![screen shot 2560-05-24 at 9 22 42 pm](https://cloud.githubusercontent.com/assets/8809681/26408136/31968b34-40c7-11e7-9bc1-b045c915926e.png)

![screen shot 2560-05-24 at 9 24 42 pm](https://cloud.githubusercontent.com/assets/8809681/26408249/729e29a2-40c7-11e7-96c6-d09d9bb252c6.png)

when I enter Variants, Prices, and Product Properties , same error appear... 
other sings looks like working.
if you have some Idea pls teach me ..
thanks

**Comment by weblike-guy** [comment]
I found fix issue

**Comment by weblike-guy** [comment]
thanks your info..

I could finish many part of set up.

I follow your fix log form git.

If lost way again, I will ask you.

thanks ^^
