### ISSUE TITLE
Which version works with solidus?

### ISSUE THREAD

**Issue by exocode** [solidusio-contrib/solidus_globalize#67]
Hi there,

I am struggling since one whole day with an installation of Solidus_globalize. Can someone tell me please which version of solidus_globalize works with Solidus for production? 

The following chart suggests none of them:

http://extensions.solidus.io/

Which version can I use? Or is that list „real“? Do I have to go lower?

Any help would be appreciated... 

Thank you

**Comment by aaongr** [comment]
Hello :)
I am having the same issue...
Any news on this?

**Comment by exocode** [comment]
I completely dropped Solidus and moved to Shopify. It's also written in Ruby, so you can extend it by your own plugins. It's maintained and works really well, so I can focus on things that matter...

**Comment by aaongr** [comment]
If I do not include the `solidus_i18n` gem and just copy the required locales locally then the bundle complete successfully !

**Comment by kennyadsl** [comment]
@exocode Shopify is not free and open-source so it's hard to compare. I'm happy that you have found a good platform for your business though. 🙂 

This extension now works with all supported Solidus versions, going to close this one.
