### ISSUE TITLE
Product properties autocomplete  issue

### ISSUE THREAD

**Issue by connecticus** [solidusio-contrib/solidus_globalize#7]
Only if solidus_globalize in use we have have had  autocomplete  issue in Product properties name. 
It is going from Spree 3.x

Product properties name autocomplete is not working, 'Uncaught TypeError: Cannot read property 'label' of null' is appears in JS log.

Solidus 1.1.x and 1.2.x

**Comment by spaghetticode** [comment]
👍

**Comment by kennyadsl** [comment]
This is fixed in globalize with https://github.com/globalize/globalize/pull/707.
